#!/usr/bin/env bash
#
# Install, inspect, or remove the daily AI Daily Learn LaunchAgent.
#
# The plist is GENERATED rather than shipped as a static file, so it always
# carries this machine's real $HOME and this checkout's real script path — a
# committed plist would hardcode one developer's username and silently fail
# for everyone else.
#
# Usage:
#   install_schedule.sh                  # install / reinstall at 11:00
#   install_schedule.sh --time 09:30     # install at a different time
#   install_schedule.sh --status         # show whether it is registered
#   install_schedule.sh --uninstall      # remove it
#
# A LaunchAgent is used rather than crontab because launchd runs a missed job
# when the laptop wakes; cron silently skips it if the machine was asleep.

set -uo pipefail

USER_NAME="$(id -un)"
LABEL="com.${USER_NAME}.ai-daily-learn"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNNER="$SCRIPT_DIR/run_daily.sh"
ROOT="${AI_LEARNING_DIR:-$HOME/ai_learning}"
DOMAIN="gui/$(id -u)"

HOUR=11
MINUTE=0
ACTION=install

say() { printf '[schedule] %s\n' "$*"; }
die() { printf '[schedule] ERROR: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --time)
      [ $# -ge 2 ] || die "--time needs an argument, e.g. --time 09:30"
      case "$2" in
        [0-9]|[0-9][0-9]|[0-9]:[0-9][0-9]|[0-9][0-9]:[0-9][0-9]) ;;
        *) die "invalid --time '$2' (expected H, HH, H:MM or HH:MM)" ;;
      esac
      HOUR="${2%%:*}"
      case "$2" in *:*) MINUTE="${2##*:}" ;; *) MINUTE=0 ;; esac
      HOUR=$((10#$HOUR)); MINUTE=$((10#$MINUTE))
      [ "$HOUR" -le 23 ]   || die "hour out of range: $HOUR"
      [ "$MINUTE" -le 59 ] || die "minute out of range: $MINUTE"
      shift 2 ;;
    --uninstall) ACTION=uninstall; shift ;;
    --status)    ACTION=status;    shift ;;
    -h|--help)   sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

case "$ACTION" in
  status)
    if launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1; then
      say "$LABEL is registered"
      launchctl print "$DOMAIN/$LABEL" 2>/dev/null |
        grep -E 'state =|runs =|last exit code|"Hour"|"Minute"|run_daily\.sh' | sed 's/^[[:space:]]*/  /'
    else
      say "$LABEL is NOT registered (run this script with no arguments to install)"
      exit 1
    fi
    exit 0 ;;
  uninstall)
    launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null && say "unloaded $LABEL" || say "$LABEL was not loaded"
    [ -f "$PLIST" ] && { rm -f "$PLIST"; say "removed $PLIST"; }
    say "done — the daily job will no longer run"
    exit 0 ;;
esac

# --- Install ------------------------------------------------------------------
[ -f "$RUNNER" ] || die "runner not found at $RUNNER"
[ -x "$RUNNER" ] || chmod +x "$RUNNER"

mkdir -p "$HOME/Library/LaunchAgents" "$ROOT/.logs"

# $HOME/.local/bin is included since that's the common place for a
# user-installed `claude` or an auth helper to live. Without the usual PATH
# entries, launchd's minimal environment can leave claude unable to run or
# authenticate.
JOB_PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by install_schedule.sh. Re-run that script instead of editing this file. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${RUNNER}</string>
    </array>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>${HOUR}</integer>
        <key>Minute</key>
        <integer>${MINUTE}</integer>
    </dict>

    <key>WorkingDirectory</key>
    <string>${ROOT}</string>

    <key>StandardOutPath</key>
    <string>${ROOT}/.logs/run.log</string>
    <key>StandardErrorPath</key>
    <string>${ROOT}/.logs/run.err.log</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${JOB_PATH}</string>
        <key>HOME</key>
        <string>${HOME}</string>
    </dict>

    <key>RunAtLoad</key>
    <false/>
    <key>AbandonProcessGroup</key>
    <false/>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
PLIST_EOF

plutil -lint "$PLIST" >/dev/null || die "generated plist failed plutil -lint: $PLIST"

launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null
launchctl bootstrap "$DOMAIN" "$PLIST" || die "launchctl bootstrap failed"

launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1 || die "job did not register after bootstrap"

printf -v HHMM '%02d:%02d' "$HOUR" "$MINUTE"
say "installed $LABEL — runs daily at $HHMM"
say "  runner : $RUNNER"
say "  logs   : $ROOT/.logs/run.log"
say "  run now: launchctl start $LABEL"
say "  remove : $(basename "${BASH_SOURCE[0]}") --uninstall"
